package teacher.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import teacher.dao.AssignmentDAO;
import teacher.dao.TeacherDAO;
import static teacher.gui.TeacherLoginFrame.a;
import static teacher.gui.TeacherLoginFrame.s;
import static teacher.gui.TeacherLoginFrame.tr;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Arpit
 */
public class TeacherSubjectFrame extends javax.swing.JFrame {

    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form TeacherSubjectFrame
     *
     * @throws java.sql.SQLException
     */
    public TeacherSubjectFrame() throws SQLException {
        initComponents();
        super.setLocationRelativeTo(null);
        loadassignment(s.getSubject_id());
        teacherNameLabel.setText(tr.getName());
        subjectNameLabel.setText(s.getSubject_name());
        AssignmentList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        profilebtn = new javax.swing.JButton();
        signoutbtn = new javax.swing.JButton();
        teacherNameLabel = new javax.swing.JLabel();
        teacherPicLabel = new javax.swing.JPanel();
        subjectNameLabel = new javax.swing.JLabel();
        generateReportbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        DiscussionPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        addAssignmentbtn = new javax.swing.JButton();
        removeAssignmentbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignmentList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        profilebtn.setBackground(new java.awt.Color(0, 102, 204));
        profilebtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        profilebtn.setForeground(new java.awt.Color(255, 255, 255));
        profilebtn.setText("Profile");
        profilebtn.setBorder(null);
        profilebtn.setBorderPainted(false);
        profilebtn.setContentAreaFilled(false);
        profilebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilebtn.setOpaque(true);
        profilebtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                profilebtnFocusGained(evt);
            }
        });
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });

        signoutbtn.setBackground(new java.awt.Color(0, 102, 204));
        signoutbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        signoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        signoutbtn.setText("Sign Out");
        signoutbtn.setBorder(null);
        signoutbtn.setContentAreaFilled(false);
        signoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutbtn.setOpaque(true);
        signoutbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signoutbtnFocusGained(evt);
            }
        });
        signoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutbtnActionPerformed(evt);
            }
        });

        teacherNameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        teacherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherNameLabel.setText("Teacher Name");

        teacherPicLabel.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout teacherPicLabelLayout = new javax.swing.GroupLayout(teacherPicLabel);
        teacherPicLabel.setLayout(teacherPicLabelLayout);
        teacherPicLabelLayout.setHorizontalGroup(
            teacherPicLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        teacherPicLabelLayout.setVerticalGroup(
            teacherPicLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        subjectNameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        subjectNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        subjectNameLabel.setText("Subject Name");

        generateReportbtn.setBackground(new java.awt.Color(0, 102, 204));
        generateReportbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        generateReportbtn.setForeground(new java.awt.Color(255, 255, 255));
        generateReportbtn.setText("Generate Report");
        generateReportbtn.setBorder(null);
        generateReportbtn.setBorderPainted(false);
        generateReportbtn.setContentAreaFilled(false);
        generateReportbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateReportbtn.setOpaque(true);
        generateReportbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                generateReportbtnFocusGained(evt);
            }
        });
        generateReportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportbtnActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(teacherPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(subjectNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teacherNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backbtn)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subjectNameLabel)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(teacherNameLabel)
                        .addComponent(teacherPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DiscussionPane.setBackground(new java.awt.Color(0, 102, 255));
        DiscussionPane.setForeground(new java.awt.Color(51, 51, 51));
        DiscussionPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        DiscussionPane.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        DiscussionPane.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        DiscussionPane.addTab("Discussion", jPanel5);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        studenttable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studenttable.setForeground(new java.awt.Color(51, 51, 51));
        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Roll No", "name", "Marks", "Submitted"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studenttable.setColumnSelectionAllowed(true);
        studenttable.setGridColor(new java.awt.Color(255, 255, 255));
        studenttable.setRowHeight(50);
        studenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(studenttable);
        studenttable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (studenttable.getColumnModel().getColumnCount() > 0) {
            studenttable.getColumnModel().getColumn(0).setPreferredWidth(4);
            studenttable.getColumnModel().getColumn(1).setPreferredWidth(10);
            studenttable.getColumnModel().getColumn(2).setPreferredWidth(8);
            studenttable.getColumnModel().getColumn(3).setPreferredWidth(8);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        DiscussionPane.addTab("Students", jPanel4);

        addAssignmentbtn.setBackground(new java.awt.Color(255, 255, 255));
        addAssignmentbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addAssignmentbtn.setForeground(new java.awt.Color(51, 51, 51));
        addAssignmentbtn.setText("+ Add Assignment");
        addAssignmentbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAssignmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAssignmentbtnActionPerformed(evt);
            }
        });

        removeAssignmentbtn.setBackground(new java.awt.Color(255, 255, 255));
        removeAssignmentbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        removeAssignmentbtn.setForeground(new java.awt.Color(51, 51, 51));
        removeAssignmentbtn.setText("-  Remove Assignment");
        removeAssignmentbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeAssignmentbtn.setEnabled(false);
        removeAssignmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssignmentbtnActionPerformed(evt);
            }
        });

        AssignmentList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AssignmentList.setForeground(new java.awt.Color(51, 51, 51));
        AssignmentList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AssignmentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignmentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AssignmentList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeAssignmentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(addAssignmentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DiscussionPane))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addAssignmentbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeAssignmentbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(DiscussionPane, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilebtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profilebtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_profilebtnFocusGained

    private void signoutbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signoutbtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_signoutbtnFocusGained

    private void generateReportbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_generateReportbtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_generateReportbtnFocusGained

    private void addAssignmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssignmentbtnActionPerformed
        new TeacherAddAssignment().setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_addAssignmentbtnActionPerformed

    private void removeAssignmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssignmentbtnActionPerformed
        if (this.AssignmentList.getSelectedIndices().length > 0) {
            int[] selectedIndices = AssignmentList.getSelectedIndices();
            for (int i = selectedIndices.length - 1; i >= 0; i--) {
                try {
                    AssignmentDAO.removeassignment(listModel.getElementAt(i).toString(), tr.getTeacher_id(), s.getSubject_id());
                } catch (SQLException ex) {
                    Logger.getLogger(TeacherSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                listModel.removeElementAt(selectedIndices[i]);

            }
        }
    }//GEN-LAST:event_removeAssignmentbtnActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        new TeacherProfile("").setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_profilebtnActionPerformed

    private void signoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutbtnActionPerformed
        new TeacherLoginFrame().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_signoutbtnActionPerformed

    private void generateReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportbtnActionPerformed
        new TeacherReport().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_generateReportbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        try {
            new TeacherFrame(tr.getTeacher_id()).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TeacherSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void AssignmentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentListMouseClicked
        removeAssignmentbtn.setEnabled(true);
        try {
            
            a = AssignmentDAO.getAssignmentDetails(AssignmentList.getSelectedValue(), s.getSubject_id());
            
            studenttable.setModel(AssignmentDAO.getassignmentmodel(a.getAssignment_id(), s.getSem()));
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(TeacherSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AssignmentListMouseClicked

    private void studenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttableMouseClicked

        String roll_no = (String) studenttable.getModel().getValueAt(studenttable.getSelectedRow(),0);
        try {
            new Studentmarks(roll_no).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TeacherSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_studenttableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TeacherSubjectFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TeacherSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AssignmentList;
    private javax.swing.JTabbedPane DiscussionPane;
    private javax.swing.JButton addAssignmentbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton generateReportbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton profilebtn;
    private javax.swing.JButton removeAssignmentbtn;
    private javax.swing.JButton signoutbtn;
    private javax.swing.JTable studenttable;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JLabel teacherNameLabel;
    private javax.swing.JPanel teacherPicLabel;
    // End of variables declaration//GEN-END:variables

    public void loadassignment(String sid) throws SQLException {
        ArrayList<String> l = TeacherDAO.getTeacherAssignment(sid);
        l.forEach((item) -> {
            listModel.addElement(item);
        });

    }
}
