package admin.gui;

import admin.dao.admindao;
import admin.pojo.Admin;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Arpit
 */
public class AdminFrame extends javax.swing.JFrame {
    
    static Admin a = null;

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        
    }
    
    public AdminFrame(String user) throws SQLException {
        initComponents();
        a = admindao.getAdminDetails(user); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdminProfile = new javax.swing.JButton();
        btnAdminSignOut = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();
        btnRemoveTeacher = new javax.swing.JButton();
        btnRemoveStudent = new javax.swing.JButton();
        editteacherbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 600));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        btnAdminProfile.setBackground(new java.awt.Color(0, 102, 204));
        btnAdminProfile.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAdminProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminProfile.setText("Profile");
        btnAdminProfile.setBorder(null);
        btnAdminProfile.setBorderPainted(false);
        btnAdminProfile.setContentAreaFilled(false);
        btnAdminProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminProfile.setOpaque(true);
        btnAdminProfile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAdminProfileFocusGained(evt);
            }
        });
        btnAdminProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProfileActionPerformed(evt);
            }
        });

        btnAdminSignOut.setBackground(new java.awt.Color(0, 102, 204));
        btnAdminSignOut.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAdminSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminSignOut.setText("Sign Out");
        btnAdminSignOut.setBorder(null);
        btnAdminSignOut.setBorderPainted(false);
        btnAdminSignOut.setContentAreaFilled(false);
        btnAdminSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminSignOut.setOpaque(true);
        btnAdminSignOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAdminSignOutFocusGained(evt);
            }
        });
        btnAdminSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(864, Short.MAX_VALUE)
                .addComponent(btnAdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnAddTeacher.setBackground(new java.awt.Color(222, 222, 222));
        btnAddTeacher.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnAddTeacher.setForeground(new java.awt.Color(51, 51, 51));
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.setBorder(null);
        btnAddTeacher.setBorderPainted(false);
        btnAddTeacher.setContentAreaFilled(false);
        btnAddTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTeacher.setOpaque(true);
        btnAddTeacher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAddTeacherFocusGained(evt);
            }
        });
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        btnRemoveTeacher.setBackground(new java.awt.Color(222, 222, 222));
        btnRemoveTeacher.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnRemoveTeacher.setForeground(new java.awt.Color(51, 51, 51));
        btnRemoveTeacher.setText("Remove Teacher");
        btnRemoveTeacher.setBorder(null);
        btnRemoveTeacher.setBorderPainted(false);
        btnRemoveTeacher.setContentAreaFilled(false);
        btnRemoveTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveTeacher.setOpaque(true);
        btnRemoveTeacher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRemoveTeacherFocusGained(evt);
            }
        });
        btnRemoveTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTeacherActionPerformed(evt);
            }
        });

        btnRemoveStudent.setBackground(new java.awt.Color(222, 222, 222));
        btnRemoveStudent.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnRemoveStudent.setForeground(new java.awt.Color(51, 51, 51));
        btnRemoveStudent.setText("Remove Student");
        btnRemoveStudent.setBorder(null);
        btnRemoveStudent.setBorderPainted(false);
        btnRemoveStudent.setContentAreaFilled(false);
        btnRemoveStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveStudent.setOpaque(true);
        btnRemoveStudent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRemoveStudentFocusGained(evt);
            }
        });
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        editteacherbtn.setBackground(new java.awt.Color(222, 222, 222));
        editteacherbtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        editteacherbtn.setForeground(new java.awt.Color(51, 51, 51));
        editteacherbtn.setText("Edit Teacher Details");
        editteacherbtn.setBorder(null);
        editteacherbtn.setBorderPainted(false);
        editteacherbtn.setContentAreaFilled(false);
        editteacherbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editteacherbtn.setOpaque(true);
        editteacherbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editteacherbtnFocusGained(evt);
            }
        });
        editteacherbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editteacherbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editteacherbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(366, 366, 366))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(editteacherbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnRemoveTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTeacherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAddTeacherFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTeacherFocusGained

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        new AddTeacher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnRemoveTeacherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRemoveTeacherFocusGained

    }//GEN-LAST:event_btnRemoveTeacherFocusGained

    private void btnRemoveTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTeacherActionPerformed
        new AdminRemoveTeacher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRemoveTeacherActionPerformed

    private void btnRemoveStudentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRemoveStudentFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveStudentFocusGained

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        new AdminRemoveStudent().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void editteacherbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editteacherbtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_editteacherbtnFocusGained

    private void editteacherbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editteacherbtnActionPerformed
        new AdminEditTeacher().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_editteacherbtnActionPerformed

    private void btnAdminProfileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAdminProfileFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminProfileFocusGained

    private void btnAdminSignOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAdminSignOutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminSignOutFocusGained

    private void btnAdminProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProfileActionPerformed
        new AdminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminProfileActionPerformed

    private void btnAdminSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSignOutActionPerformed
        new teacher.gui.TeacherLoginFrame().setVisible(true);
        this.dispose();//new AddTeacher().setVisible(true);

        //this.dispose();
    }//GEN-LAST:event_btnAdminSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnAdminProfile;
    private javax.swing.JButton btnAdminSignOut;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnRemoveTeacher;
    private javax.swing.JButton editteacherbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
